// @vitest-environment jsdom
/**
 * Importer tests, run against REAL files:
 *
 *   resolume-arena-preferences.xml   Arena 7.27.0's own AdvancedOutput.xml from
 *                                    this machine — a DeckLink capture output,
 *                                    so the raster has to be inferred
 *   resolume-arena-preset.xml        a real saved Advanced Output preset, 3
 *                                    slices in one screen on a virtual device
 *   blend-calc-export.xml            generated by running blend-calc's own test
 *                                    suite with BLEND_CALC_XML_OUT set
 *   pixel-peeker-export.xml          }  generated by running pixel-peeker's own
 *   pixel-peeker-interchange.json    }  suite with PP_WRITE_ARTEFACTS set
 *
 * None of them are hand-written, which is the point: a fixture invented to match
 * the parser proves only that the parser matches itself.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { blendCalcDefaults, isBlendCalcProject, parseBlendCalcProject, staleAxisFor } from './blendcalc'
import { detectAndParse } from './detect'
import { parsePixelPeekerInterchange } from './pixelpeeker'
import { parseResolumeXml } from './resolume'

const FIX = join(__dirname, '../../test/fixtures')
const read = (f: string) => readFileSync(join(FIX, f), 'utf8')

describe('Resolume: real Arena AdvancedOutput.xml', () => {
  const xml = read('resolume-arena-preferences.xml')

  it('reads the screen, its slice and the composition size', () => {
    const r = parseResolumeXml(xml, 'AdvancedOutput.xml')
    expect(r.source).toBe('resolume')
    expect(r.composition).toEqual({ widthPx: 1920, heightPx: 1080 })
    expect(r.outputs).toHaveLength(1)
    const out = r.outputs[0]!
    expect(out.name).toBe('Trailer Screen')
    expect(out.regions).toHaveLength(1)
  })

  it('infers the raster from slice bounds when the device is a capture card', () => {
    // This screen goes to a DeckLink. Arena records a deviceId and an idHash for
    // it but no dimensions, so the only evidence is the slice's OutputRect.
    const out = parseResolumeXml(xml).outputs[0]!
    expect(out.rasterSource).toBe('slice-bounds')
    expect(out.widthPx).toBe(3840)
    expect(out.heightPx).toBe(2160)
    expect(out.device).toContain('DeckLink')
    expect(out.notes.join(' ')).toMatch(/inferred/i)
  })

  it('warns that the raster was inferred rather than read', () => {
    const r = parseResolumeXml(xml)
    expect(r.warnings.join(' ')).toMatch(/inferred from slice bounds/i)
  })

  it('carries the slice input rect through for composition mode', () => {
    const out = parseResolumeXml(xml).outputs[0]!
    expect(out.compositionRect).toEqual({ x: 0, y: 0, width: 3840, height: 2160 })
  })
})

describe('Resolume: real Arena Advanced Output preset', () => {
  const xml = read('resolume-arena-preset.xml')

  it('finds the ScreenSetup nested inside XmlState', () => {
    const r = parseResolumeXml(xml, 'output_map_1.xml')
    expect(r.outputs).toHaveLength(1)
    expect(r.composition).toEqual({ widthPx: 2944, heightPx: 1280 })
  })

  it('trusts the declared virtual device size over the slice bounds', () => {
    const out = parseResolumeXml(xml).outputs[0]!
    expect(out.name).toBe('OUTPUT MAP 1')
    expect(out.rasterSource).toBe('declared')
    expect(out.widthPx).toBe(3840)
    expect(out.heightPx).toBe(1720)
  })

  it('reads all three slices', () => {
    const out = parseResolumeXml(xml).outputs[0]!
    expect(out.regions).toHaveLength(3)
    for (const region of out.regions) {
      expect(region.rect.width).toBeGreaterThan(0)
      expect(region.rect.height).toBeGreaterThan(0)
      expect(region.input).toBeDefined()
    }
  })
})

describe('Resolume: Blend Calc’s own export', () => {
  const xml = read('blend-calc-export.xml')

  it('reads a 3x2 projector array as six outputs', () => {
    const r = parseResolumeXml(xml, 'blend-calc-demo.xml')
    expect(r.outputs).toHaveLength(6)
    expect(r.outputs.map((o) => o.name)).toEqual([
      'Blend Calc Demo R1C1',
      'Blend Calc Demo R1C2',
      'Blend Calc Demo R1C3',
      'Blend Calc Demo R2C1',
      'Blend Calc Demo R2C2',
      'Blend Calc Demo R2C3',
    ])
    for (const out of r.outputs) {
      expect(out.rasterSource).toBe('declared')
      expect(out.widthPx).toBe(1920)
      expect(out.heightPx).toBe(1200)
    }
  })

  it('recovers the overlap from the input rects', () => {
    const r = parseResolumeXml(xml)
    const [a, b] = [r.outputs[0]!.compositionRect!, r.outputs[1]!.compositionRect!]
    // Adjacent projectors overlap, so the second starts before the first ends.
    expect(b.x).toBeLessThan(a.x + a.width)
    expect(a.x + a.width - b.x).toBeGreaterThan(0)
  })

  it('spans the full composition canvas', () => {
    const r = parseResolumeXml(xml)
    expect(r.composition).toEqual({ widthPx: 4992, heightPx: 1664 })
    const right = Math.max(...r.outputs.map((o) => o.compositionRect!.x + o.compositionRect!.width))
    const bottom = Math.max(...r.outputs.map((o) => o.compositionRect!.y + o.compositionRect!.height))
    expect(right).toBe(4992)
    expect(bottom).toBe(1664)
  })
})

describe('Resolume: Pixel Peeker’s own export', () => {
  const xml = read('pixel-peeker-export.xml')

  it('reads the processor screen and its per-port slices', () => {
    const r = parseResolumeXml(xml, 'wall.xml')
    expect(r.outputs).toHaveLength(1)
    const out = r.outputs[0]!
    expect(out.rasterSource).toBe('declared')
    expect(out.widthPx).toBe(3200)
    expect(out.heightPx).toBe(1800)
    // One slice per patched port.
    expect(out.regions.length).toBeGreaterThan(1)
  })
})

describe('Pixel Peeker interchange', () => {
  const doc = JSON.parse(read('pixel-peeker-interchange.json'))

  it('makes one output per processor, sized to what it drives', () => {
    const r = parsePixelPeekerInterchange(doc)
    expect(r.source).toBe('pixel-peeker')
    expect(r.projectName).toBe('Test Wall')
    expect(r.outputs).toHaveLength(1)
    const out = r.outputs[0]!
    expect(out.name).toBe('MX40 Pro 1')
    expect(out.widthPx).toBe(3200)
    expect(out.heightPx).toBe(1800)
    expect(out.rasterSource).toBe('computed')
  })

  it('carries every cabinet through as a region, with chain order', () => {
    const out = parsePixelPeekerInterchange(doc).outputs[0]!
    const cabinets = out.regions.filter((r) => r.order !== undefined)
    expect(cabinets).toHaveLength(144)
    // Chain order is 1-based and restarts per port.
    expect(Math.min(...cabinets.map((c) => c.order!))).toBe(1)
    for (const cab of cabinets) {
      expect(cab.rect.width).toBe(200)
      expect(cab.rect.height).toBe(200)
    }
  })

  it('keeps every cabinet inside the processor raster', () => {
    const out = parsePixelPeekerInterchange(doc).outputs[0]!
    for (const region of out.regions) {
      expect(region.rect.x).toBeGreaterThanOrEqual(0)
      expect(region.rect.y).toBeGreaterThanOrEqual(0)
      expect(region.rect.x + region.rect.width).toBeLessThanOrEqual(out.widthPx)
      expect(region.rect.y + region.rect.height).toBeLessThanOrEqual(out.heightPx)
    }
  })

  it('reports the wall signal format as context', () => {
    const r = parsePixelPeekerInterchange(doc)
    expect(r.warnings.join(' ')).toMatch(/8-bit, 60 Hz/)
  })

  it('refuses a Pixel Peeker PROJECT file, naming the export that works', () => {
    expect(() => parsePixelPeekerInterchange({ schema: 'pixel-peeker/1', name: 'x' })).toThrow(
      /Export → JSON/,
    )
  })
})

describe('Blend Calc design file', () => {
  const manual = {
    name: 'Manual Rig',
    units: 'metric',
    screen: { geometry: { kind: 'flat', width: 12, height: 4 }, gain: 1 },
    array: { columns: 3, rows: 1, fitMode: 'manual', hOverlap: 0.2, vOverlap: 0.2 },
    projectorId: 'some-library-id',
    lensId: null,
  }

  it('is recognised structurally, since the file carries no schema field', () => {
    expect(isBlendCalcProject(manual)).toBe(true)
    expect(isBlendCalcProject({ schema: 'pixel-peeker/1' })).toBe(false)
    expect(isBlendCalcProject({ name: 'x' })).toBe(false)
  })

  it('lays a 3-wide array out on the same pitch rule Blend Calc uses', () => {
    const r = parseBlendCalcProject(manual, {
      nativeWidth: 1920,
      nativeHeight: 1200,
      hOverlap: 0.2,
      vOverlap: 0.2,
    })
    expect(r.outputs).toHaveLength(3)
    // pitch = 1920 * (1 - 0.2) = 1536
    expect(r.outputs.map((o) => o.compositionRect!.x)).toEqual([0, 1536, 3072])
    // Canvas comes off the last tile's right edge, never a separate rounding.
    expect(r.composition).toEqual({ widthPx: 3072 + 1920, heightPx: 1200 })
  })

  it('marks the overlap bands as regions on the projectors that have them', () => {
    const r = parseBlendCalcProject(manual, {
      nativeWidth: 1920,
      nativeHeight: 1200,
      hOverlap: 0.2,
      vOverlap: 0.2,
    })
    // Outer projectors blend on one side, the middle one on both.
    expect(r.outputs[0]!.regions).toHaveLength(1)
    expect(r.outputs[1]!.regions).toHaveLength(2)
    expect(r.outputs[2]!.regions).toHaveLength(1)
    expect(r.outputs[0]!.regions[0]!.rect).toEqual({
      x: 1920 - 384,
      y: 0,
      width: 384,
      height: 1200,
    })
  })

  it('ignores the overlap on an axis with only one tile', () => {
    const single = { ...manual, array: { ...manual.array, columns: 1, rows: 1 } }
    const r = parseBlendCalcProject(single, {
      nativeWidth: 1920,
      nativeHeight: 1200,
      hOverlap: 0.2,
      vOverlap: 0.2,
    })
    expect(r.outputs).toHaveLength(1)
    expect(r.composition).toEqual({ widthPx: 1920, heightPx: 1200 })
    expect(r.outputs[0]!.regions).toHaveLength(0)
  })

  it('knows which axis a fit mode leaves stale in the file', () => {
    expect(staleAxisFor('fit-width')).toBe('v')
    expect(staleAxisFor('fit-height')).toBe('h')
    expect(staleAxisFor('manual')).toBeNull()
  })

  it('warns loudly when the stored overlap is a solver output', () => {
    const fit = { ...manual, array: { ...manual.array, fitMode: 'fit-width' as const, rows: 2 } }
    const r = parseBlendCalcProject(fit, {
      nativeWidth: 1920,
      nativeHeight: 1200,
      hOverlap: 0.2,
      vOverlap: 0.2,
    })
    const text = r.warnings.join(' ')
    expect(text).toMatch(/SOLVES the vertical overlap/)
    expect(text).toMatch(/stale input/)
    expect(blendCalcDefaults(fit).staleAxis).toBe('v')
  })

  it('always says the raster came from the user, not the file', () => {
    const r = parseBlendCalcProject(manual, {
      nativeWidth: 2560,
      nativeHeight: 1600,
      hOverlap: 0.2,
      vOverlap: 0.2,
    })
    expect(r.warnings.join(' ')).toMatch(/supplied by you/)
  })

  it('refuses to lay out without a raster', () => {
    expect(() =>
      parseBlendCalcProject(manual, {
        nativeWidth: 0,
        nativeHeight: 0,
        hOverlap: 0.2,
        vOverlap: 0.2,
      }),
    ).toThrow(/native resolution is required/)
  })
})

describe('detectAndParse', () => {
  it('routes each real fixture to the right importer', () => {
    for (const [file, expected] of [
      ['resolume-arena-preferences.xml', 'resolume'],
      ['resolume-arena-preset.xml', 'resolume'],
      ['blend-calc-export.xml', 'resolume'],
      ['pixel-peeker-export.xml', 'resolume'],
      ['pixel-peeker-interchange.json', 'pixel-peeker'],
    ] as const) {
      const got = detectAndParse(read(file), file)
      expect(got.kind, file).toBe('ready')
      if (got.kind !== 'ready') continue
      expect(got.result.source, file).toBe(expected)
      expect(got.result.outputs.length, file).toBeGreaterThan(0)
    }
  })

  it('asks for options rather than guessing on a Blend Calc design', () => {
    const got = detectAndParse(
      JSON.stringify({
        name: 'Rig',
        screen: { geometry: { kind: 'flat', width: 10, height: 4 } },
        array: { columns: 2, rows: 1, fitMode: 'fit-width', hOverlap: 0.25, vOverlap: 0.1 },
      }),
      'rig.blendcalc.json',
    )
    expect(got.kind).toBe('needs-blend-calc-options')
    if (got.kind !== 'needs-blend-calc-options') return
    expect(got.defaults.columns).toBe(2)
    expect(got.defaults.hOverlap).toBe(0.25)
    expect(got.defaults.staleAxis).toBe('v')
  })

  it('names the right export when handed a Pixel Peeker project file', () => {
    expect(() =>
      detectAndParse(JSON.stringify({ schema: 'pixel-peeker/1', name: 'w' }), 'w.json'),
    ).toThrow(/Export → JSON/)
  })

  it('explains itself on a Resolume composition', () => {
    expect(() =>
      detectAndParse('<?xml version="1.0"?><Composition name="x"></Composition>', 'x.avc'),
    ).toThrow(/advanced output/i)
  })

  it('rejects malformed JSON with the parser’s own complaint', () => {
    expect(() => detectAndParse('{ "a": ', 'x.json')).toThrow(/not valid JSON/)
  })

  it('rejects a file that is neither', () => {
    expect(() => detectAndParse('hello world', 'notes.txt')).toThrow(/Unrecognised file/)
  })
})
